# add  known_host 수정 2
name: Deploy with Docker to Ubuntu Server

on:
  push:
    branches:
      - main  # main branch에서 commit이 있는 경우 (Commit/Push)
    

jobs:
  deploy:
    runs-on: ubuntu-latest # ubuntu 최종버전
    permissions:
      contents: read 

    steps:
    # 코드 체크 아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # JDK 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    # gradle 권한 부여
    - name: Setup Gradle permissions
      run: |
        chmod +x ./gradlew
    # gradle build
    
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build -x test
# war 파싱 => clean 전체 삭제 => 다시 build
    - name: Login in to DockerHub
      run: |
        echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest .
        docker push ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest
# SSH : 암호화 통신 => 개인키(id_ed25519)를 가지고 AWS에 접속
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with: 
        Ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
# 등록 => 서버키 등록

    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 43.201.73.68 >> ~/.ssh/known_hosts
#  실행 
#  정지 => docker stop image명
#  삭제 => docker rm image
    - name: Depoly on Server using DockerHub image
      run: | 
        ssh ubuntu@43.201.73.68 << 'EOF'
          sudo docker stop spring-boot-app || true
          sudo docker rm spring-boot-app || true
          sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest
          sudo docker run -d --name spring-boot-app --restart always -p 8080:8080 ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-app:latest
        EOF
