# add  known_host 수정 2
name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # main branch에서 commit이 있는 경우
    

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # 코드 체크 아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # JDK 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
    # gradle 권한 부여
    - name: Setup Gradle permissions
      run: |
        chmod +x ./gradlew
    # gradle build
    
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Set SSH key permission 
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.SERVER_SSH_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:   
        ssh-private-key: ${{secrets.SERVER_SSH_KEY}}

    - name: Add known_hosts
      run: |
        ssh-keyscan -H rsa 13.125.23.177 >> ~/.ssh/known_hosts

    - name: Deploy to Server with rsync
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/libs/*.war ubuntu@13.125.23.177:~/app

    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_res ubuntu@13.125.23.177 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/app/SpringBootLastProject-0.0.1-SNAPSHOT.war > log.txt> &1 &EOF
